[package]
name = "koreader-highlights"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
chrono = "0.4"
full_moon = "0.19"
walkdir = "2"
rusqlite = { version = "0.31", features = ["bundled"] }
